# Generated by Django 3.0.7 on 2020-07-04 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default=None, max_length=100)),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('proposal', 'proposal'), ('eproof', 'eproof'), ('powerpoint', 'powerpoint'), ('brochure', 'brochure'), ('certificate', 'certificate'), ('manual', 'manual')], default='proposal', max_length=20)),
                ('document_file', models.FileField(upload_to='listings/documents/%Y/%m/%d/')),
                ('cover_file', models.ImageField(default='listings/default/preview1.png', upload_to='listings/covers/%Y/%m/%d/')),
                ('image1_file', models.ImageField(default='listings/default/preview1.png', upload_to='listings/previews/%Y/%m/%d/')),
                ('image2_file', models.ImageField(default='listings/default/preview1.png', upload_to='listings/previews/%Y/%m/%d/')),
                ('image3_file', models.ImageField(default='listings/default/preview1.png', upload_to='listings/previews/%Y/%m/%d/')),
            ],
        ),
    ]
